# Site settings
title: Meu Blog
email: wesleyvilanovadelimatorres@gmail.com
description: "Um blog sobre desenvolvimento e tecnologia."
baseurl: "/Artigos"
url: "https://wesleyvilanova.github.io"
github_url: "https://github.com/WesleyVilaNova"  # Corrigido para github_url
linkedin_url: "https://www.linkedin.com/in/wesley-vila-nova/"  # Corrigido para linkedin_url

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
