# Site settings
title: "Códigos e Conhecimento: Um Blog de Desenvolvimento Android"
email: wesleyvilanovadelimatorres@gmail.com
description: "Vamos conversar sobre desenvolvimento e tecnologia?"
baseurl: "/Artigos"
url: "https://wesleyvilanova.github.io"
github_url: "https://github.com/WesleyVilaNova"
linkedin_url: "https://www.linkedin.com/in/wesley-vila-nova/"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
