# Site settings
title: Meu Blog
email: wesleyvilanovadelimatorres@gmail.com
description: "Um blog sobre desenvolvimento e tecnologia."
baseurl: "/Artigos"
url: "https://wesleyvilanova.github.io"
twitter_username: seuusuario
github_username: seuusuario

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
