# Site settings
title: Meu titulo testes entendendo
email: wesleyvilanovadelimatorres@gmail.com
description: "Um blog sobre desenvolvimento e tecnologia 123"
baseurl: "/Artigos"
url: "https://wesleyvilanova.github.io"
github_url: "https://github.com/WesleyVilaNova"
linkedin_url: "https://www.linkedin.com/in/wesley-vila-nova/"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
